features: [ TRIAGE_DISCUSSIONS, TRIAGE_ISSUES_AND_PULL_REQUESTS, SET_AREA_LABEL_COLOR, NOTIFY_QE, PUSH_TO_PROJECTS ]

projects:
  rules:
    - labels: [kind/bug]
      project: 1
      issues: true
      pullRequests: true
      status: Todo
    - labels: [kind/enhancement]
      project: 1
      issues: true
      pullRequests: true
      status: Todo

triage:
  rules:
    - id: kind-bug
      labels: [kind/bug]
      titleBody: "bug"
      notify: [rubenskj]
      
    - id: kind-enhancement
      labels: [kind/enhancement]
      titleBody: "(feature|enhancement)"
      notify: [rubenskj]
      
    - id: asset-core-system
      labels: [area/system]
      titleBody: "(drag|draggable|input controller|highlighter|options system)"
      files:
        - Assets/Inventory/Scripts/Controllers/
      notify: [rubenskj]
      
    - id: docs.rushassets.com
      labels: [area/docs.rushassets]
      titleBody: "(docs.rushassets|docs rushassets)"
      notify: [rubenskj]
      
    - id: documentations
      labels: [area/documentation]
      titleBody: "(docs|documentation|documentations|readme|.md)"
      notify: [rubenskj]
     
    - id: youtube
      labels: [area/social-media,area/youtube]
      titleBody: "(youtube|yt)"
      notify: [rubenskj]
      
    - id: instagram
      labels: [area/social-media,area/instagram]
      titleBody: "(instagram|insta)"
      notify: [rubenskj]
      
    - id: demo
      labels: [area/demonstration]
      titleBody: "(demo|demonstration|demos|demonstrations)"
      notify: [rubenskj]
      
    - id: world
      labels: [area/world]
      titleBody: "(2d world|3d world|world)"
      notify: [rubenskj]
        
    - id: ux-ui
      labels: [area/ux-ui]
      titleBody: "(ux|ui|user interface|user experience)"
      notify: [rubenskj]
      
    - id: save-system
      labels: [area/save-system]
      titleBody: "(save|save system|saves)"
      notify: [rubenskj]
      
    - id: integration
      labels: [area/integration]
      titleBody: "(integration|api)"
      notify: [rubenskj]
      
    - id: grids
      labels: [area/grids]
      titleBody: "(inventory grid|grid inventory|grid inventories|grid)"
      notify: [rubenskj]
      
    - id: right-options
      labels: [area/right-options]
      titleBody: "(right-options|options|selection|item option)"
      notify: [rubenskj]
      
    - id: holders
      labels: [area/holders]
      titleBody: "(holders|item holder|container holder|holder)"
      notify: [rubenskj]
      
    - id: items
      labels: [area/items]
      titleBody: "(items|containers|item|container|item data so)"
      notify: [rubenskj]
      
    - id: item-containers
      labels: [area/containers]
      titleBody: "(container item|container|containers)"
      notify: [rubenskj]
      
    - id: icon-size
      labels: [area/images,area/icon-size]
      titleBody: "(icon-sizes|item icons|items icons|item icon image)"
      notify: [rubenskj]
      
    - id: audio
      labels: [area/audio]
      titleBody: "(audio|audios|sound|sounds|cue)"
      notify: [rubenskj]
      
    - id: scroll
      labels: [area/scroll]
      titleBody: "(scroll|scrollable)"
      notify: [rubenskj]
      
    - id: windows
      labels: [env/windows]
      titleBody: "windows"
      
    - id: m1
      labels: [env/m1]
      titleBody: "\\bm1\\b"
      notify: [rubenskj]
        
# Add more rules in here
        
  qe:
    notify: [rubenskj]
