features: [ TRIAGE_DISCUSSIONS, TRIAGE_ISSUES_AND_PULL_REQUESTS, SET_AREA_LABEL_COLOR, NOTIFY_QE ]

triage:
  rules:
    - id: kind-bug
      labels: [kind/bug]
      titleBody: "bug"
      notify: [rubenskj]
      
    - id: kind-enhancement
      labels: [kind/enhancement]
      titleBody: "(feature|enhancement)"
      notify: [rubenskj]
      
    - id: asset-core-system
      labels: [area/system]
      titleBody: "(drag|draggable|input controller|highlighter|options system)"
      notify: [rubenskj]
      
    - id: documentations
      labels: [area/documentation]
      titleBody: "(docs|documentation|)"
      notify: [rubenskj]
        
# Add more rules in here
        
  qe:
    notify: [rubenskj]
