features: [ALL]

triage:
  rules:
    - id: bug-label
      labels: [kind/bug]
      titleBody: "bug"
      notify: [rubenskj]
      
    - id: asset-core-system
      labels: [area/system]
      titleBody: "(drag|draggable|input controller|highlighter|options system)"
      notify: [rubenskj]
        
  qe:
    notify: [rubenskj]
