name: Bug Report
description: Report a bug in Ultimate Grid Inventory
labels: [ "kind/bug" ]
assignees:
  - RubensKj
  
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the bug
      description: >-
        Describe the issue you are experiencing here to communicate to the
        maintainers. Tell us what you were trying to do and what happened.

        Provide a clear and concise description of what the problem is.
  - type: textarea
    attributes:
      label: Expected behavior
      description: >-
        Describe the expected behavior clearly and concisely.
  - type: textarea
    attributes:
      label: Actual behavior
      description: >-
        Describe the actual behavior clearly and concisely.
  - type: textarea
    attributes:
      label: How to Reproduce?
      description: >-
        Link to a video, gif or screenshot (preferably a video or gif) or attach an archive containing the reproducer to the issue.
      placeholder: |
        Reproducer:

        Steps to reproduce the behavior:
        1. 
        2. 
        3.        
  - type: markdown
    attributes:
      value: |
        ## Asset Information
  - type: input
    attributes:
      label:  Asset version
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below.
        Please note, you can attach screenshots or screen recordings here, by
        dragging and dropping files in the field below.
